djecommerce/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('order-summary/', order_summary, name='order-summary'),
    path('product/<slug>/', product_detail, name='product-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-product-from-cart/<slug>/',
         remove_single_product_from_cart, name='remove-single-product-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')

]

# urlpatterns = [
#     path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
# ]

djecommerce/djecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

djecommerce/core/forms.py
from django import forms
from .fields import EmptyChoiceField
from .models import Coupon, OrderProduct, STATE_CHIOSES, CITY_CHIOSES, NEIGHBOUR_CHIOSES

PAYMENT_CHOICES = (
    ('O', 'Online'),
    ('C', 'Credit Card')
)


class CheckoutForm(forms.Form):
    payment_option = EmptyChoiceField(choices=PAYMENT_CHOICES)
    state = EmptyChoiceField(choices=STATE_CHIOSES,
                             required=False, empty_label='---select---')
    city = EmptyChoiceField(choices=CITY_CHIOSES,
                            required=False, empty_label='---select---')
    neighbour = EmptyChoiceField(
        choices=NEIGHBOUR_CHIOSES, required=False, empty_label='---select---')
    postal_address = forms.CharField(
        max_length=200, required=False)
    plaque = forms.CharField(max_length=5, required=False)
    unit = forms.CharField(max_length=30, required=False)
    postal_code = forms.CharField(
        max_length=10, help_text='postal code must be 10 numbers without dash', required=False)
    receiver_fname = forms.CharField(max_length=100)
    receiver_lname = forms.CharField(max_length=100)
    receiver_national_code = forms.CharField(
        max_length=10, help_text='national code must be 10 numbers without dash')
    receiver_phone_number = forms.CharField(
        max_length=11, help_text='Example: 09123456789')
    address_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

    def is_valid(self):
        is_valid = super(CheckoutForm, self).is_valid()
        if not is_valid:
            return False
        address_id = self.cleaned_data.get('address_id')
        state = self.cleaned_data.get('state')
        city = self.cleaned_data.get('city')
        neighbour = self.cleaned_data.get('neighbour')
        postal_address = self.cleaned_data.get('postal_address')
        plaque = self.cleaned_data.get('plaque')
        unit = self.cleaned_data.get('unit')
        postal_code = self.cleaned_data.get('postal_code')

        new_add_req = False
        if state or city or neighbour or postal_address or plaque or unit or postal_code:
            new_add_req = True
        if new_add_req and address_id:
            is_valid = False
        return is_valid


class CouponForm(forms.Form):
    code = forms.CharField(max_length=100)

    def is_valid(self):
        is_valid = super(CouponForm, self).is_valid()
        if not is_valid:
            return (False, '')
        code = self.cleaned_data['code']
        coupon_qs = Coupon.objects.filter(code=code)
        if coupon_qs.exists():
            return (True, coupon_qs[0])
        else:
            self.errors['invalid_coupon'] = 'Coupon does not exist; please enter valid code.'
            return (False, '')


class RefundForm(forms.Form):
    order_product_id = forms.IntegerField()
    quantity = forms.IntegerField()
    reason = forms.CharField(widget=forms.Textarea)

    def is_valid(self):
        is_valid = super(RefundForm, self).is_valid()
        if not is_valid:
            return (False, '')

        order_product_id = self.cleaned_data['order_product_id']
        quantity = self.cleaned_data['quantity']
        order_product_qs = OrderProduct.objects.filter(id=order_product_id)

        if order_product_qs.exists():
            order_product = order_product_qs[0]
            if quantity <= order_product.quantity:
                return (True, order_product)
            else:
                self.errors['invalid_order_product_quantity'] = 'your request for refund is more than order product quantity.'
                return (False, '')

        else:
            self.errors['invalid_order_product'] = 'Order Product does not exist; please enter valid id.'
            return (False, '')

djecommerce/core/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Product, OrderProduct, Order, Address, Refund  # , Receiver
from .serializers import ProductSerializer, OrderSerializer
from .forms import CheckoutForm, CouponForm, RefundForm


def home(request):
    '''
    returns jsonify of all products
    '''
    serializer = ProductSerializer(Product.objects.all(), many=True)
    data = {
        'products': serializer.data
    }
    return JsonResponse(data)


@login_required
def order_summary(request):
    try:
        # order_serializer = OrderSerializer(
        #     Order.objects.get(user=request.user, ordered=False))
        # data = {
        #     'order': order_serializer.data,
        # }
        # return JsonResponse(data)
        order = Order.objects.get(user=request.user, ordered=False)
        return render(request, 'core/order_summary.html', {'order': order})

    except Order.DoesNotExist:
        data = {
            'error': 'You do not have an active order'
        }
        return JsonResponse(data)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    product_serializer = ProductSerializer(product)
    data = {
        'product': product_serializer.data
    }
    return JsonResponse(data)


@login_required
def add_to_cart(request, slug):
    '''
    If user has more than one active order
        recognizes the problem
    else if user did not have an active order
        create one and add product to his order
    else if user has an active order
        if the order product was in the order
            increase the quantity
        else
            add product to order
    '''
    product = get_object_or_404(Product, slug=slug)
    pro_ser_data = ProductSerializer(product).data
    order_product, created = OrderProduct.objects.get_or_create(
        user=request.user,
        product=product,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    n_orders = order_qs.count()

    # if (n_orders := order_qs.count()) > 1:
    if n_orders > 1:
        data = {'error': f'You have {n_orders} active orders!'}
        return JsonResponse(data)

    # elif order_qs.exists():
    elif n_orders == 1:
        order = order_qs[0]
        # check if the order product is in the order
        if order.products.filter(product__slug=product.slug).exists():
            order_product.quantity += 1
            order_product.save()
            data = {
                'message': f'the fallowing product quantity was updated to {order_product.quantity}',
                'product': pro_ser_data
            }
            return JsonResponse(data)
        else:
            order.products.add(order_product)
            data = {
                'message': 'This item was added to your cart.',
                'product': pro_ser_data
            }
            return JsonResponse(data)
    # else:
    elif n_orders == 0:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.products.add(order_product)
        data = {
            'message': 'Order created for you and the fallowing product was added to your cart.',
            'product': pro_ser_data
        }
        return JsonResponse(data)


@login_required
def remove_from_cart(request, slug):
    '''
    completely remove order product from order without considering quantity
    '''
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    n_orders = order_qs.count()
    if n_orders == 1:
        order = order_qs[0]
        # check if the order product is in the order
        if order.products.filter(product__slug=product.slug).exists():
            order_product = OrderProduct.objects.filter(
                product=product, user=request.user, ordered=False)[0]
            order.products.remove(order_product)
            order_product.delete()
            data = {
                'message': 'This item was removed from your cart.'
            }
            return JsonResponse(data)
        else:
            data = {
                'error': 'This item was not in your cart'
            }
            return JsonResponse(data)
    else:
        data = {
            'error': f'Number of your active orders: {n_orders}'
        }
        return JsonResponse(data)


@login_required
def remove_single_product_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    n_orders = order_qs.count()
    if n_orders == 1:
        order = order_qs[0]
        # check if the order product is in the order
        if order.products.filter(product__slug=product.slug).exists():
            order_product = OrderProduct.objects.filter(
                product=product, user=request.user, ordered=False)[0]
            if order_product.quantity > 1:
                order_product.quantity -= 1
                order_product.save()
                data = {
                    'message': f'Product quantity was updated to {order_product.quantity}.'
                }
                return JsonResponse(data)
            else:
                order.products.remove(order_product)
                order_product.delete()
                data = {
                    'message': 'order_product removed from your order'
                }
                return JsonResponse(data)
        else:
            data = {
                'message': 'This item was not in your cart'
            }
            return JsonResponse(data)
    else:
        data = {
            'error': f'Number of your active orders: {n_orders}'
        }
        return JsonResponse(data)


@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class CheckoutView(View):
    '''
    TODO: when the user want to recive his order
    electronic payment
        discount code
        electronic payment gateway
    pay with credit card
        discount code
    '''
    login_required = True

    def get(self, request):
        try:
            order = Order.objects.get(user=request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'order': order
            }
            address_qs = Address.objects.filter(user=request.user)
            if address_qs.exists():
                context.update({
                    'addresses': address_qs
                })
            return render(request, "core/checkout.html", context)
        except Order.DoesNotExist:
            messages.warning(request, "You do not have an active order")
            return redirect("core:home")

    def post(self, request):
        form = CheckoutForm(request.POST)
        # form.is_valid()
        # return JsonResponse(form.cleaned_data)
        try:
            order = Order.objects.get(user=request.user, ordered=False)

        except Order.DoesNotExist:
            return JsonResponse({'error': 'You do not have an active order'})

        if form.is_valid():
            # create receiver
            # receiver_fname = form.cleaned_data['receiver_fname']
            # receiver_lname = form.cleaned_data['receiver_lname']
            # receiver_national_code = form.cleaned_data['receiver_national_code']
            # receiver_phone_number = form.cleaned_data['receiver_phone_number']
            # receiver = Receiver.objects.create(first_name=receiver_fname, last_name=receiver_lname,
            #                                    national_code=receiver_national_code, phone_number=receiver_phone_number)
            # create address with receiver

            if 'address_id' in form.cleaned_data and form.cleaned_data['address_id']:
                address = Address.objects.get(
                    id=form.cleaned_data['address_id'])
            else:
                state = form.cleaned_data['state']
                city = form.cleaned_data['city']
                neighbour = form.cleaned_data['neighbour']
                postal_address = form.cleaned_data['postal_address']
                plaque = form.cleaned_data['plaque']
                unit = form.cleaned_data['unit']
                postal_code = form.cleaned_data['postal_code']
                address = Address(user=request.user, state=state, city=city, neighbour=neighbour,
                                  postal_address=postal_address, plaque=plaque, unit=unit, postal_code=postal_code,)
            address.rec_fname = form.cleaned_data['receiver_fname']
            address.rec_lname = form.cleaned_data['receiver_lname']
            address.rec_national_code = form.cleaned_data['receiver_national_code']
            address.rec_phone_number = form.cleaned_data['receiver_phone_number']
            address.save()

            # assign the address to the order
            order.address = address
            order.save()
            payment_option = form.cleaned_data['payment_option']
            if payment_option == "C":
                # user want to pay with credit card
                # process the product for transportation
                return JsonResponse({'message': 'Your order was saved and it will process for transfer.'})
            elif payment_option == "O":
                # TODO: shaparak
                return HttpResponse('shaparak')
            else:
                return JsonResponse({'error': 'Invalid payment option selected'})
        else:
            return JsonResponse({'errors': form.errors, 'data': form.cleaned_data})


class AddCouponView(View):

djecommerce/core/templates/core/add_coupon.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Coupon form</h2>
    <div class="d-flex justify-content-center row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Add Coupon</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

djecommerce/core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Django Ecommerce</title>
</head>
<body>
  {% if messages %}
  <div class="mt-5 pt-4">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
      </div>
  {% endif %}

  {% block content %}
  {% endblock %}
</body>
</html>

djecommerce/core/templates/core/checkout.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<main>
  <div class="container wow fadeIn">
    <div id="message-container"></div>
    <div id="addresses-container">
      {% if addresses %}
      <h3>You have field these addresses</h3>
      {% for address in addresses %}
      {{ address.postal_address }}
      <button onclick="setAddress('{{ address.id }}')" class="btn btn-success">Use This Address</button>
      <hr>
      {% endfor %}
      {% endif %}
    </div>
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="checkbox" onchange="imReceiver()" id='imReceiver_id'> I am my own receiver
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
          </form>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        {% include "core/order_snippet.html" %}
      </div>
    </div>
  </div>
</main>
<!-- <style>
  body {
    background-color: #180e45;
  }

  * {
    color: wheat;
  }

  .card-body {
    background-color: wheat;
  }

  .card-body * {
    color: black;
  }
</style> -->
<script>
  document.querySelector('html').style = 'scroll-behavior: smooth;';

  function setAddress(addressID) {
    address_id = document.querySelector('input[name=address_id]').value = addressID;
    document.querySelector('#addresses-container').style.display = 'none';

    let toBoHide = ['state', 'city', 'neighbour', 'postal_address', 'plaque', 'unit', 'postal_code'];
    for (let i = 0; i < toBoHide.length; i++) {
      document.querySelector(`div#div_id_${toBoHide[i]}`).style.display = 'none';
      //      try {
      //        document.querySelector(`input[name=${toBoHide[i]}]`).style.display = 'none';
      //      } catch (error) {
      //          //console.log(error)
      //      }
      //      try {
      //        document.querySelector(`select[name=${toBoHide[i]}]`).style.display = 'none';
      //      } catch (error) {
      //          //console.log(error)
      //      }

    }
  }

  function imReceiver() {
    let checkBox = document.querySelector('input[type=checkbox]');
    let receiver_fname = document.querySelector('input[name=receiver_fname]');
    let receiver_lname = document.querySelector('input[name=receiver_lname]');
    let user_lname = '{{ user.first_name }}'
    let user_fname = '{{ user.last_name }}'
    if (checkBox.checked) {
      if (user_fname === '' || user_lname === '' ) {
        window.scrollTo(0, 0);
        makeAlert('info', "You do not have a full name or surname Please fill them in manually")
        setTimeout(() => {checkBox.checked = false;}, 1000)

      } else {
      receiver_fname.value = '{{ user.first_name }}';
      receiver_lname.value = '{{ user.last_name }}';
      receiver_fname.setAttribute('readonly', '');
      receiver_lname.setAttribute('readonly', '');
      }
    } else {
      receiver_fname.value = '';
      receiver_lname.value = '';
      receiver_fname.removeAttribute('readonly');
      receiver_lname.removeAttribute('readonly');
    }
  }

  function makeAlert(type, message) {
    let div = document.querySelector('#message-container');
    const alertClasses = ['alert', `alert-${type}`, 'alert-dismissible', 'fade', 'show'];
    div.classList.add(...alertClasses);
    div.role = 'alert';
    div.innerText = message;

    let btn = document.createElement('button');
    btn.type = 'button';
    btn.classList = 'close';
    btn.setAttribute('data-dismiss', 'alert');
    btn.setAttribute('aria-label', 'Close');
    btn.onclick = () => {
      if (0 >= div.style.opacity) {
        clearInterval(btnInterval);
      }
      var btnInterval = setInterval(() => {div.style.opacity -= 0.1}, 10)
    }


    let span = document.createElement('span');
    span.setAttribute('aria-hidden', 'true')
    span.innerText = 'X';

    btn.appendChild(span);
    div.appendChild(btn);
  }


</script>
{% endblock content %}

djecommerce/core/templates/core/order_snippet.html
<div class="col-md-12 mb-4">
  <h4 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted">Your cart</span>
  <span class="badge badge-secondary badge-pill">{{ order.products.count }}</span>
  </h4>
  <ul class="list-group mb-3 z-depth-1">
  {% for order_product in order.products.all %}
  <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
      <h6 class="my-0">{{ order_product.quantity }} x {{ order_product.product.title}}</h6>
      <small class="text-muted">{{ order_product.product.description}}</small>
      </div>
      <span class="text-muted">${{ order_product.get_final_price }}</span>
  </li>
  {% endfor %}
  {#
  {% if order.coupon %}
  <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
      <h6 class="my-0">Promo code</h6>
      <small>{{ order.coupon.code }}</small>
      </div>
      <span class="text-success">-${{ order.coupon.amount }}</span>
  </li>
  {% endif %}
  #}
  <li class="list-group-item d-flex justify-content-between">
      <span>Total (USD)</span>
      <strong>${{ order.get_total }}</strong>
  </li>
  </ul>

</div>

djecommerce/core/templates/core/order_summary-html.html
{% extends "core/base.html" %}

{% block content %}
<main>
  <div class="container">
    <div class="jumbotron">
      <h2 class="display-4">Hi ali!</h2>
      <p class="lead">This is your order summary.</p>
    </div>
    <div class="d-flex justify-content-center row">
      <div class="table-responsive">
        <table class="table table-hover table-bordered"> <!-- table-striped -->
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">First</th>
              <th scope="col">Last</th>
              <th scope="col">Handle</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr class="table-secondary">
              <th scope="row">3</th>
              <td colspan="2">Larry</td>
              <!-- <td>the Bird</td> -->
              <td>@twitter</td>
            </tr>
            {% if order.coupon %}
            <tr>
              <td colspan="4"><b>Coupon</b></td>
              <td><b>-${{ order.coupon.amount }}</b></td>
            </tr>
            {% endif %}
            {% if order.get_total %}
            <tr>
                <td colspan="4"><b>Order Total</b></td>
                <td><b>${{ order.get_total }}</b></td>
            </tr>
            <tr>
                <td colspan="5">
                <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                </td>
            </tr>
            {% endif %}








          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

djecommerce/core/templates/core/order_summary.html
{% extends "core/base.html" %}

{% block content %}
<script>
  tdList = document.getElementsByTagName('td');
  for (let i = 0; i < tdList.length; i++) {
    const td = tdList[i];
    td.classList.add('text-center');
  }
</script>
<main>
  <div class="container">
    <div class="jumbotron" style="padding: 3rem 2rem;">
      <h2 class="display-4">Hi ali!</h2>
      <p class="lead">This is your order summary.</p>
    </div>

    <div class="d-flex justify-content-center row">
      <div class="table-responsive">
        <table class="table table-hover table-bordered"> <!-- table-striped -->
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product Title</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total Product Price</th>
            </tr>
          </thead>
          <tbody>
            {% for order_product in order.products.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ order_product.product.title }}</td>
              <td>{{ order_product.product.price }}</td>
              <td>
                  <a href="{% url 'core:remove-single-product-from-cart' order_product.product.slug %}" class="btn btn-danger"><i class="bi bi-dash-square">-</i></a>
                  {{ order_product.quantity }}
                  <a href="{% url 'core:add-to-cart' order_product.product.slug %}" class="btn btn-success"><i class="bi bi-plus-square">+</i></a>
              </td>
              <td>
              {% if order_product.product.discount_price %}
                ${{ order_product.get_total_discount_product_price }}
                <span class="badge badge-primary">Saving ${{ order_product.get_amount_saved }}</span>
              {% else %}
                ${{ order_product.get_total_product_price }}
              {% endif %}
                <a style='color: red;' href="{% url 'core:remove-from-cart' order_product.product.slug %}">
                  <i class="fas fa-trash float-right"></i>
                </a>
              </td>
            </tr>

            {% empty %}
            <tr class="table-info">
              <td colspan='4'>
                Your cart is empty
              </td>
              <td colspan="1">
                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
              </td>
            </tr>
            {% endfor %}

            {% if order.coupon %}
            <tr>
                <td colspan="4"><b>Coupon</b></td>
                <td><b>-${{ order.coupon.amount }}</b></td>
            </tr>
            {% endif %}

            {% if order.get_total %}
            <tr>
                <td colspan="4"><b>Order Total</b></td>
                <td><b>${{ order.get_total }}</b></td>
            </tr>
            <tr class="table-info">
                <td colspan="5">
                <a class='btn btn-warning float-right ml-2' href='{% url "core:checkout" %}'>Proceed to checkout</a>
                <a class='btn btn-primary float-right' href='{% url "core:home" %}'>Continue shopping</a>
                </td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

djecommerce/core/templates/core/request_refund.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Refund form</h2>
    <div class="d-flex justify-content-center row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Add Coupon</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}